version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 3306:3306
    networks:
      - activityspot-network

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    image: play_spot_app-api:dev
    volumes:
      - ./backend:/myapp
      - ./backend/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3001:3000
    networks:
      - activityspot-network
    depends_on:
      - db

  web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      # - ./frontend:/usr/src
      - /app/node_modules
      - ./frontend/app:/app
    command: sh -c "yarn && yarn start"
    image: play_spot_app-web:dev
    ports:
      - "4000:3000"
    networks:
      - activityspot-network

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  activityspot-network:
    external: true
