version: "3"

services:
  # =========ローカルと本番切り替え===========
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - /tmp/dockerdir:/etc/mysql/conf.d/
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - activityspot-network
  # ======================================

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    # =========ローカルと本番切り替え===========
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # command: bash -c "mkdir -p tmp/pids && bundle exec puma -C config/puma.rb"
    command: bash -c "bundle exec puma -C config/puma.rb"
    # ======================================
    # image: play_spot_app-api
    image: 788422463177.dkr.ecr.ap-northeast-1.amazonaws.com/play-spot-repository_api
    volumes:
      - ./backend:/myapp
      - ./backend/vendor/bundle:/myapp/vendor/bundle
      # - ./backend:/play-spot-app/backend
      # - ./backend/vendor/bundle:/play-spot-app/backend/vendor/bundle
      # - .:/play-spot-app
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
      # - public-data:/play-spot-app/backend/public
      # - tmp-data:/play-spot-app/backend/tmp
      # - log-data:/play-spot-app/backend/log
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
    # ports:
    #   - 3001:3000
    networks:
      - activityspot-network
    # =========ローカルと本番切り替え===========
    # depends_on:
    #   - db
  # ======================================

  web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - ./frontend/app:/app
      # - ./frontend:/usr/src/app
      # - public-data:/play-spot-app/backend/public
      # - tmp-data:/play-spot-app/backend/tmp
    # working_dir: /app
    # command: sh -c "yarn && yarn build"
    # image: play_spot_app-web
    image: 788422463177.dkr.ecr.ap-northeast-1.amazonaws.com/play-spot-repository_web
    ports:
      - "80:3000"
      # - "443:3000"
    networks:
      - activityspot-network

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data:
  # db-data:

networks:
  activityspot-network:
    external: true
