# version: "3"

# services:
#   # =========ローカルと本番切り替え===========
#   # db:
#   #   image: mysql:8.0
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: password
#   #   command: --default-authentication-plugin=mysql_native_password
#   #   volumes:
#   #     - mysql-data:/var/lib/mysql
#   #     - /tmp/dockerdir:/etc/mysql/conf.d/
#   #   ports:
#   #     - 3306:3306
#   #   networks:
#   #     - activityspot-network
#   # ======================================

#   api:
#     build:
#       context: ./backend/
#       dockerfile: Dockerfile
#     # =========ローカルと本番切り替え===========
#     # command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     command: bundle exec puma -C config/puma.rb -e production
#     # ======================================
#     image: rails:dev
#     volumes:
#       - ./backend:/myapp
#       - ./backend/vendor/bundle:/myapp/vendor/bundle
#     environment:
#       TZ: Asia/Tokyo
#       RAILS_ENV: development
#     ports:
#       - 3001:3000
#     networks:
#       - activityspot-network
#   # =========ローカルと本番切り替え===========
#   # depends_on:
#   #   - db
#   # ======================================

#   front:
#     build:
#       context: ./frontend/
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend:/usr/src/app
#     command: sh -c "cd app && yarn && yarn start"
#     ports:
#       - "4000:3000"
#     networks:
#       - activityspot-network

# volumes:
#   mysql-data:

# networks:
#   activityspot-network:
#     external: true

version: "3"
services:
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/activityspot
      - public-data:/activityspot/public
      - tmp-data:/activityspot/tmp
      - log-data:/activityspot/log
    ports:
      - 3001:3000
    networks:
      - activityspot-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: activityspot_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - activityspot-network

  web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - public-data:/activityspot/public
      - tmp-data:/activityspot/tmp
    ports:
      - "4000:3000"
    depends_on:
      - app
    networks:
      - activityspot-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  activityspot-network:
    external: true
